name: Update works

on:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v2
    - name: checkout aozorabuno.git
      run: |
        git clone --depth 1 https://github.com/aozorabunko/aozorabunko.git
    - name: copy only html (card) files
      run: |
        cd aozorabunko
        cp --parents cards/*/*/*.html  ../
    - name: git config && commit
      run: |
        git config --global user.email "takahashim@users.noreply.github.com"
        git config --global user.name "github-actions-bot"
        git add --all cards
        CURDATE=`date "+%Y%m%d"`
        git commit -m "[ci skip] update htmls ${CURDATE}"
    - name: push
      run: |
        git remote set-url origin https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
        git push origin HEAD:master
